// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBydUjuWDgap0O9b44RMtwWGT71hvb89WA',
    appId: '1:214609037413:web:e29086edac602e95b01e8c',
    messagingSenderId: '214609037413',
    projectId: 'first-project-4cc28',
    authDomain: 'first-project-4cc28.firebaseapp.com',
    storageBucket: 'first-project-4cc28.appspot.com',
    measurementId: 'G-7WGZXCMWHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaTzLQaDQuAZBGoDkr6R9Nhsm1Wo2XVJI',
    appId: '1:214609037413:android:b429342a98349b7eb01e8c',
    messagingSenderId: '214609037413',
    projectId: 'first-project-4cc28',
    storageBucket: 'first-project-4cc28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAVYgs7uJrXnlLz_ILmR0lAjxefO3CSIk',
    appId: '1:214609037413:ios:4a258c949c788c64b01e8c',
    messagingSenderId: '214609037413',
    projectId: 'first-project-4cc28',
    storageBucket: 'first-project-4cc28.appspot.com',
    iosClientId: '214609037413-idtvind0gpjk098f4c5acj21c87krfnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.mylogin191',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAVYgs7uJrXnlLz_ILmR0lAjxefO3CSIk',
    appId: '1:214609037413:ios:4a258c949c788c64b01e8c',
    messagingSenderId: '214609037413',
    projectId: 'first-project-4cc28',
    storageBucket: 'first-project-4cc28.appspot.com',
    iosClientId: '214609037413-idtvind0gpjk098f4c5acj21c87krfnm.apps.googleusercontent.com',
    iosBundleId: 'com.example.mylogin191',
  );
}
